### ISSUE TITLE
got a terminal error when attempt to edit the file by uploading a different file

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1136] opened 2017-05-31 23:28 UTC
This issue can be reproduced by following these steps:
1. Navigate to this [link](https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/Accession_ID=RBKUSC20160801PRO4) (but honestly this can be reproduced on *every single* record page that has entities in related tables.)
2. Scroll down to a related table with entities in it, and select the `edit icon` on one of the entities. (Do not close this `record` page)
3. When the `recordedit` page loads, click on `Submit Data`.
4. When the `record` page loads, click the `Edit`.
5. When `recordedit` loads again, click `Submit Data`. You should be presented with one of the following errors at this point. 

The error in Mozilla Firefox:
```
editRecordRequests[id] is undefined
   RecordController/window.updated@https://dev.rebuildingakidney.org/~jchudy/chaise/record/record.controller.js?v=283028e69a80aeaad08e17f0f05ce2d6:217:17
   success@https://dev.rebuildingakidney.org/~jchudy/chaise/recordedit/form.controller.js?v=a015d91688bcb0faeef1f1d05ceb6e27:262:29
   processQueue@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:15961:28
   scheduleProcessQueue/<@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:15977:27
   $eval@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17229:16
   $digest@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17045:15
   $apply@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17337:13
   done@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11572:36
   completeRequest@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11778:7
   requestLoaded@https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11711:9
   ```

The error in Google Chrome:
```
TypeError: Cannot read property 'schema' of undefined
    at RecordController.window.updated (https://dev.rebuildingakidney.org/~jchudy/chaise/record/record.controller.js?v=283028e69a80aeaad08e17f0f05ce2d6:217:47)
    at success (https://dev.rebuildingakidney.org/~jchudy/chaise/recordedit/form.controller.js?v=a015d91688bcb0faeef1f1d05ceb6e27:262:43)
    at processQueue (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:15961:28)
    at https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:15977:27
    at Scope.$eval (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17229:28)
    at Scope.$digest (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17045:31)
    at Scope.$apply (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17337:24)
    at done (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11572:47)
    at completeRequest (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11778:7)
    at XMLHttpRequest.requestLoaded (https://dev.rebuildingakidney.org/~jchudy/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:11711:9)
```

**Comment by jrchudy** [comment] 2017-06-01 19:23
I can't reproduce the above error case, but going to that link and editing the file provides me with a different `409 Conflict Error`.

This same error can be observed here:
https://dev.rebuildingakidney.org/chaise/recordset/#2/Protocol:Figure_last_updated

**Comment by jrchudy** [comment] 2017-06-01 22:54
Furthermore, I can see this same error with a direct request to `ermrest`.

**Comment by ljpearlman** [comment] 2017-06-02 01:58
This is related to the way I've been doing row-level security. I have a fix.

**Comment by hongsudt** [comment] 2017-06-02 17:47
@jrchudy we can probably close this issue..

**Comment by jrchudy** [comment] 2017-06-02 18:01
I can no longer reproduce this issue after the changes @ljpearlman made yesterday to the Protocol schema.

**Comment by hongsudt** [comment] 2017-06-02 23:25
I am reopening this issue since I still see the terminal server error pretty frequently.

**Comment by hongsudt** [comment] 2017-06-02 23:26
It seems like the submission was done since when I refreshed the page, I did see the updated value..

**Comment by jrchudy** [comment] 2017-06-03 02:40
PR #1140 addresses this issue. I added a case inside the `window.update` function in `record.controller.js` so that the function doesn't try to run before the browser loads the `record` UI.

The purpose of the `window.update` function is to synchronize when a related table has an entity created or edited. `window.update` fires after the `window.onFocus()` function to keep track of what related tables previously had create/edit actions taken from them. And then removes them from the array after that table is _update_.

**Comment by jrchudy** [comment] 2017-06-06 22:35
See the original issue description for an update on how to reproduce.

**Comment by jrchudy** [comment] 2017-06-07 17:26
The PR addressing this issue has been merged into master.

Reassigning to @hongsudt to verify it has been fixed. Please see the updated description at the top for how to reproduce this issue.

**Closed** 2017-07-27 20:49 UTC
Labels: bug, recordedit
