### ISSUE TITLE
ACL Policy Handling

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#1334] opened 2017-10-12 18:52 UTC
This issue mentions a list of cases where we need to determine what ACL to check and how Chaise app should response.

* Record app:
  * main entity columns
    * if not selectable but enumerable: Hide??   
  * related table
    * if not selectable but enumerable: ???
* Navbar
  * Hiding/showing links in navbar according to policy.

Please add any more cases to this issue if you find

**Comment by hongsudt** [comment] 2018-03-01 20:41
duplicate of #1366

**Closed by hongsudt** 2018-03-01 20:41 UTC
Labels: question
