### ISSUE TITLE
Search produces invalid paging filters with null keys

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#875] opened 2016-12-16 19:26 UTC
When search chooses a key that can contain nulls, it produces invalid paging filters such as `Columnname::ge::null` when it encounters nulls.  A null can never be used in a comparison (it will always return non-truth).

I suspect the code was trying to get rows *including or after* a null value when it produced this `::ge::` constraint, considering the NULLs last sort order we always perform in ERMrest.  The correct filter would use `Columnname::null::` in this case to get the same ordering effect.

@hongsudt @svoinea

**Comment by svoinea** [comment] 2017-01-04 21:30
The problem was fixed by setting the adequate `::null::` operator for `NULL` values.

**Comment by svoinea** [comment] 2017-01-05 19:38
@hongsudt  The issue is ready for review. Please assign a reviewer.

**Closed** 2017-05-19 00:28 UTC
Labels: bug, search
