### ISSUE TITLE
Shorter maximum widths of controls in data entry form

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#416] opened 2016-06-02 18:48 UTC
When displaying, we want to limit the width of controls so they don't fill the screen. @carlkesselman points out that when you have such long controls the drop downs little arrows are all the way on the right hand side of the screen and so we lose some intuitiveness of what to do with it. But note that all the controls should have the same width as they do now, just with an upper limit on width.

**Comment by karlcz** [comment] 2016-06-07 18:13
This suggests to me that the problem is the placement or alignment of the drop-down arrow and content.  Since we can have variable length values and they are padded on the right, with field labels on the left, perhaps the drop-down arrow should also be on the left.

We have some very long values (DNA construct names) and I would hate to see them wrapped due to an arbitrary width limit if the user's screen is wide enough to display them.  Due to their weird punctuation, breaking the values on the small amounts of white-space will also be quite ugly.

As an aside, this raises a related issue of being able to encode presentation information like non-breaking spaces and/or preferred hyphenation points in controlled vocabularies...

**Comment by carlkesselman** [comment] 2016-06-07 18:18
Actually, this brings up an issue I’ve been thinking about which is should we have the ability to specify presentation for general values, or even sets of values.  For example, right now we are doing presentation level formatting for sequences (doing them in blocks of 5).  In GPCR, we are seeing an example, where it may be advantagous to take several columns and combine them into a single value using a printf type formatting string….

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 7, 2016, at 11:13 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


This suggests to me that the problem is the placement or alignment of the drop-down arrow and content. Since we can have variable length values and they are padded on the right, with field labels on the left, perhaps the drop-down arrow should also be on the left.

We have some very long values (DNA construct names) and I would hate to see them wrapped due to an arbitrary width limit if the user's screen is wide enough to display them. Due to their weird punctuation, breaking the values on the small amounts of white-space will also be quite ugly.

As an aside, this raises a related issue of being able to encode presentation information like non-breaking spaces and/or preferred hyphenation points in controlled vocabularies...

**Comment by robes** [comment] 2016-06-07 18:20
We should stick to standard UI controls and look & feel. The arrow for drop downs is always (to my knowledge) on the right.

Personally, I am not sure that I agree with this issue in the first place. For instance, I use MS Outlook. The “To:” field stretches all the way to the right of the window and on the far right side is an icon for “Search for people”. To me this is the equivalent of our situation. So yes, its not ideal, but on the other hand we are at least on par with this example. That’s my $0.02…

**Comment by karlcz** [comment] 2016-06-07 18:59
Right, is the problem that you can *only* click on that little arrow or that it is the only indication that it is a drop-down?  If the latter, should we replace a blank gray field with some lower contrast text like "Select a value..."?

Also, do we distinguish classic drop-downs where clicking anywhere opens the list, or will clicking in the main body put the cursor in a type-ahead search mode...? Are we every going to have a variant where the drop-down and/or typeahead provides *suggested* values but additional values can be entered manually?  Do we want all such behaviors lumped into one visual control or should they be distinct in look and feel?

**Comment by hongsudt** [comment] 2017-11-21 20:19
I am tagging this issue as a wishlist and close this one for now.

**Closed by hongsudt** 2017-11-21 20:19 UTC
Labels: recordedit, wishlist
