### ISSUE TITLE
Zero byte file crashes asset upload?

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1347] opened 2017-10-26 22:15 UTC
This may be a corner case we don't have to worry about but as part of a test I found it impossible to upload a zero byte file. I assume there is some divide by zero error in the asset upload handler either in chaise or ermrestjs.

**Comment by chiragsanghvi** [comment] 2017-11-08 20:24
@robes The problem is ermrest returns a 409 when we check whether a file exists. For 409's we consider that the file had a problem while uploading, so we try to upload it again and apparently the code doesn't uploads anything as there is no content to read and it is stuck.

Will this work ? I am rendering a warning and clearing the file picker when user selects a zero byte file. https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#36330/upload:file

**Comment by chiragsanghvi** [comment] 2017-11-10 23:59
This issue has been fixed in ermrestjs and merged in Master

**Closed by chiragsanghvi** 2017-11-10 23:59 UTC
Labels: bug, recordedit
