### ISSUE TITLE
Sub-menu opens off-screen

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2071] opened 2021-03-30 01:35 UTC
If you get a navbar menu near the right side of the screen, e.g. due to responsive layout on a narrow window, nested sub-menus will still attempt to open to the right and end up clipped by the viewport.

I can recreate this on CFDE by logging in and going to the data review catalog which has a "Submission System" menu towards the right side of the navbar.  Resize the window until the login/username template moves to the next line, then open the Submission System -> Vocabulary sub-menu.  It can appear partially or totally clipped depending on how narrow you make the window.

**Comment by RFSH** [comment] 2021-05-21 22:58
To provide another example, this can be seen in Facebase as well. Navigate to [this page](https://www.facebase.org/chaise/recordset/#1/isa:dataset@sort(release_date::desc::,RID)) and reduce the page width so that the last option is very close to the edge.

We need to figure out what is the best way to handle this. One obvious solution would be expanding the sub-menu to the left instead right.

**Comment by kpherwan** [comment] 2021-06-10 21:20
Hi @karlcz can you please verify if the issue is resolved now (it's merged to master). Let me know if something is missing/wrong.

**Comment by RFSH** [comment] 2021-07-29 17:40
I'm going to close this issue due to inactivity. If this is still not working as expected we should create a new issue for it.

**Closed by RFSH** 2021-07-29 17:40 UTC
