### ISSUE TITLE
Text Search on Facets is not working properly for text values representing a number

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1399] opened 2017-12-04 19:06 UTC
On `cirm-dev`, go to the `Search | Slide` link (https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:Slide) page.

The `Slide ID` facet, has for example the `20130308-mKDAWTIRI_PAS-sk-0-01-000` value.

Enter in its search box the `2013` value. It returns `No Results Found`.

The request sent to the server is:
```
https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=Microscopy:Slide/Number%20of%20Scans::gt::0;Number%20of%20Scans::lt::1/$M/ID::ciregexp::%5E%28.%2A%5B%5E0-9.%5D%29%3F0%2A**2013**%28%5B%5E0-9%5D.%2A%7C%24%29/value:=ID;count:=cnt(*)@sort(count::desc::,value)?limit=11
```

The entered `2013` valued is surrounded by some text that makes to return no rows.

`cirm-dev` is using the **ermrest** `stateful-model` branch, but the bug is re-creatable also on **ermrest** `master`.

**Comment by karlcz** [comment] 2017-12-04 19:57
This is actually the currently expected behavior of the search box in
Chaise.

We heuristically determine that the user is searching for a numeric
string (typing only decimal digits) and generate a different search
regex which will only match the "whole" number rather than an
arbitrary substring.  Substring matching produces nonsensical results
whenever there are actual numeric columns in a table.

In your case, I think it should work to search on "20130308" but it
won't work to match "2013", "2013030", "0308", etc.  Turning off this
special case for search would cause lots of other false matches when
users are actually searching for numbers.

I don't think there is any quick fix opportunity here, unless there
are significant numbers of tables w/o any numeric columns and we 
made the front-end recognize this case and drop the number guarding
regex behavior...?

**Comment by svoinea** [comment] 2017-12-05 18:03
That was an arbitrary test.

However, if I enter the same value `2013` in the search box of the results page, it works as expected,  displaying in the `Slide ID` facet only the values having the `2013` substring.

The requests sent in this case look similar in respect to the `ciregexp`:

```
https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=Microscopy:Slide/*::ciregexp::%5E%28.%2A%5B%5E0-9.%5D%29%3F0%2A2013%28%5B%5E0-9%5D.%2A%7C%24%29/$M/Number%20of%20Scans::gt::0;Number%20of%20Scans::lt::1/$M/F2:=left(Specimen%20ID)=(Microscopy:Specimen:ID)/$M/F1:=left(Experiment%20ID)=(Microscopy:Experiment:ID)/$M/RID;M:=array(M:*),F2:=array(F2:*),F1:=array(F1:*)@sort(RID)?limit=26

https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=Microscopy:Slide/*::ciregexp::%5E%28.%2A%5B%5E0-9.%5D%29%3F0%2A2013%28%5B%5E0-9%5D.%2A%7C%24%29/$M/Number%20of%20Scans::gt::0;Number%20of%20Scans::lt::1/$M/value:=ID;count:=cnt(*)@sort(count::desc::,value)?limit=11

https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/aggregate/M:=Microscopy:Slide/*::ciregexp::%5E%28.%2A%5B%5E0-9.%5D%29%3F0%2A2013%28%5B%5E0-9%5D.%2A%7C%24%29/$M/0:=min(Number%20of%20Scans),1:=max(Number%20of%20Scans)

https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/aggregate/M:=Microscopy:Slide/*::ciregexp::%5E%28.%2A%5B%5E0-9.%5D%29%3F0%2A2013%28%5B%5E0-9%5D.%2A%7C%24%29/$M/Number%20of%20Scans::gt::0;Number%20of%20Scans::lt::1/$M/0:=cnt(*)
```

**Comment by RFSH** [comment] 2017-12-06 19:39
They (search in facet and search in result) both behave the same way. They both change the "2013" search to a proper regular expression as Karl explained. The reason that the result are different is the fact that "2013" search is matching values of other columns in the result set (and not the Slide ID column).

**Comment by hongsudt** [comment] 2017-12-08 23:58
This is working as expected.. So I am closing this issue..

**Closed by hongsudt** 2017-12-08 23:58 UTC
Labels: bug
