### ISSUE TITLE
recordset not working on cirm-dev if you are not yet logged in

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1365] opened 2017-11-08 22:33 UTC
On `cirm-dev`, I issued https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:Scan .
I was directed to the login page.
After I  logged in, the URL has become: 

https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:Scan@sort(Acquisition%20Date::desc::,slide_id,filename,HTTP%20URL,bytes,Thumbnail,Microscope,Camera,Objective,Exposure%20Time,Channels,Channel%20Name,Contrast%20Method,Magnification,Light%20Source%20Intensity,Image%20Size,Scaling%20%28per%20pixel%29,DZI,czi2dzi,File%20Date,id,species,age,gene,checksum,probe,accession_number,doi,ark,mime_type,description,submitter,submitted,public_release_date,tissue,gender,age_stage,specimen_fixation,embedding_medium,staining_protocol,resolution,uri,status,last_modified,age_rank,Disambiguator,Experiment%20ID,Specimen%20ID,Probes,Experiment%20Type)

and the rendered page looks like:

![recordset](https://user-images.githubusercontent.com/1609577/32578163-0fc5eef2-c491-11e7-899e-03df674e1ed0.png)

If I am already logged in, and issue https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:Scan , the rendered page looks good.

The database does not contain the `ermrest` system columns.

**Comment by RFSH** [comment] 2017-11-09 17:50
This is happening because of the `select:false`, `enumerate:true` case which [is not fully supported by chaise/ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/issues/515). Although a simple fix for this case is forcing page reload after user logged in.
 But this combination of ACLs can cause problem in different apps. We are going to [enforce page reload after anonymous user logs in](https://github.com/informatics-isi-edu/chaise/issues/1366), but if a logged-in user has this combination of ACLs it can cause problem:

- In column level, we're not handling this combination of ACLs at the moment (The case where table is selectable but some of its columns are not) because of ermrestjs limitations. You should avoid this case until we start supporting it in ermrestjs.

- In schema/table level, we're not handling this combination of ACLs appropriately. Which means instead of just hiding that table and avoiding the read, we're letting ermrest to throw an error. Consider the case that user has `select:true` for the main table but cannot select one of the facet tables. The expected behavior in that case would be hiding the facet instead of throwing forbidden error for the whole page.

**Comment by RFSH** [comment] 2017-11-09 17:56
To explain why the URL is changing in this case, 
  - Because of ACLs, user cannot access the key of the table. When sorting, we're always appending the shortest key to the sort list. In this case, since key doesn't exist, we're using all the columns of the table.
  - Visible columns logic in ermrestjs is the only API that is currently taking care of `select:false`. Since all the columns are `select:false`, visible columns list is empty (therefore the empty table).

**Comment by svoinea** [comment] 2017-11-09 19:13
I have changed on the `cirm-dev` ACL catalog the `enumerate` to match the `select`, and that fixed it.

**Closed** 2017-11-13 23:04 UTC
Labels: bug
