### ISSUE TITLE
recordset horizontal scroll bar

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1573] opened 2018-06-20 23:59 UTC
People seem to struggle with finding the horizontal scroll bar on the recordset since the horizontal scroll-bar is not always visible.. 

What are our options to address this problem?

**Comment by jrchudy** [comment] 2018-06-21 01:30
If you have users that see this on linux or windows, we can explore more potential issues but I can't find a simple solution for those cases right now.

**Comment by karlcz** [comment] 2018-06-21 01:34
To be clear, the issue is not scrollbar showing or not.  It's that the
horizontal scrollbar is offscreen at the bottom of a scrollable
vertical region that is taller than the viewport.  It's very confusing
that the two scrollbars do not stay bound to the viewport and remain
on screen at all times.

**Comment by jrchudy** [comment] 2018-06-21 01:47
We can do something similar to what was done for `recordedit` which has a scrollbar on the top of the container as well as on the bottom of the container.

**Comment by kpherwan** [comment] 2021-06-24 01:44
Query -
Does this problem need to be solved for all tables i.e. recordset page, facet(view more), record page  OR exclusively for the recordset table?

Few alternatives - 

1. Keep a fixed max height of the table (possible 60% of viewport height) so the horizontal toolbar would be more easily visible (you don't need to vertically scroll over all the entries to find the horizontal scrollbar)

Pros - vertical scrolling is also reduced over the page i.e. user does not need to scroll through all the rows before moving on to the next table in case of record page or to move on to the pagination controls (endless scrolling reduced)

Cons - We now have two scrollbars next to each other and a slightly busy user interaction.

This is available to play around with here - https://dev.rebuildingakidney.org/~kpherwan/chaise/recordset/#2/Protocol:Protocol

<img width="1438" alt="Screen Shot 2021-06-23 at 6 39 15 PM" src="https://user-images.githubusercontent.com/78573171/123189527-d02dc780-d452-11eb-8913-6e718ede5220.png">


2. As Josh mentioned above, we can do something similar to what was done for recordedit which has a scrollbar on the top of the container as well as on the bottom of the container. This will definitely work for recordset (need to check for facet and record tables)

Pros - Makes it a consistent behavior with recordedit, the scrollbar on top would be latched

Cons - Two scrollbars together are uncommon and the problem of vertical scrolling remains i.e. if we decide to see 100 records, we have to scroll through all of them before we hit the pagination controls or the next table in case of record page)

<img width="1438" alt="Screen Shot 2021-06-23 at 6 32 17 PM" src="https://user-images.githubusercontent.com/78573171/123188771-724cb000-d451-11eb-8edc-5f651af7f732.png">

**Comment by kpherwan** [comment] 2021-08-10 20:09
Closing this issue as this has now been implemented - https://github.com/informatics-isi-edu/chaise/pull/2104

**Closed by kpherwan** 2021-08-10 20:09 UTC
Labels: UX
