### ISSUE TITLE
Required validation for foreign key columns fails when left blank.

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#500] opened 2016-07-12 05:33 UTC
@howdyjessie @jrchudy 

When you try creating an entity which has a foreign key and leave it blank while submitting, you get an Ermrest API error

```
Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: null value in column "accommodation_id" violates not-null constraint DETAIL: Failing row contains (10, null, 3.24324e+17, null).
```

![data entry app](https://cloud.githubusercontent.com/assets/1658152/16756077/6c239544-47b7-11e6-8a2a-e12c48203af9.png)

The UI validation doesn't kick in when you submit even though it is mandatory.

**Comment by hongsudt** [comment] 2016-11-01 19:00
@RFSH I think you will need to pass the NOT NULL flag to the psuedo column for this to work correctly as well..

**Comment by jrchudy** [comment] 2016-11-02 22:45
This issue is from before recordedit refactor was done. This pertains to the old instance of recordedit **without** the reference API. Closing this issue as it is a duplicate of #525.

**Closed by jrchudy** 2016-11-02 22:45 UTC
Labels: recordedit
