### ISSUE TITLE
Pass logoutURL from chaise-config.js when deleting sessions

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#413] opened 2016-06-01 18:44 UTC
Specify the currently configured (or default) Chaise logoutURL to the DELETE session call per https://github.com/informatics-isi-edu/webauthn/blob/master/doc/rest_api.md#delete-session.  

This will allow multiple chaise deployments in /var/www/html to use their own logout pages rather than the single global default specified in `ermrest_config.js`.

**Comment by svoinea** [comment] 2016-06-01 23:27
Currently, the default_logout_path from the ermrest_config.json file takes precedence over the logoutURL parameter from the chaise-config.js file. 

Does the issue require reverting the precedence order?

**Comment by mikedarcy** [comment] 2016-06-01 23:36
In my opinion, yes.  Otherwise, supporting instance-specific logout paths for multiple Chaise installs on a single host cannot be supported.  There are other configuration aspects of Chaise that support this kind of multi-tenancy, I think this should be similar.  Maybe others disagree.

**Comment by robes** [comment] 2016-06-01 23:41
So we are saying that the logout URL in chaise-config.js should override the one in ermrest config? That makes sense to me. We just need to make sure everyone knows who is responsible for deployments that this override order will change.

**Comment by svoinea** [comment] 2016-06-02 01:01
Updated the logout page based on the following precedence:

1. chaise-config['logoutURL']
2. ermrest_config['default_logout_path']
3. '/chaise/logout'. This is a default Chaise logout page that has a link to the data browser. The link can be specified by the chaise-config['dataBrowser'] parameter, or by default it is '/chaise/search'.

**Comment by svoinea** [comment] 2016-06-02 18:11
The problem was fixed in the commit fd11bb8935085d71d057129d5dfd12e005acfe0c and it is ready for review.

**Comment by ljpearlman** [comment] 2016-06-02 19:29
There's no reason for any component other than webauthn to look at the default_logout_path config variable; that's what webauthn uses when it's not supplied anything. So the sequence should be:

1. Decide whether or not chaise has a preferred logout URL (which I guess is chaise-config['logoutURL']). If so, pass it as the `logout_url` parameter to `DELETE /session`. If not, don't pass anything to `DELETE /session`.

When the DELETE /session is finished, it will return a JSON structure that includes a `redirect_url` element. Redirect the user to that URL. (See //github.com/informatics-isi-edu/webauthn/blob/master/doc/rest_api.md for more details).

This sequence of events will result in the user _eventually_ being sent to the logout URL specified in the `DELETE /session` request (if one was specified) or to the `default_logout_url` (if not). It's important to let webauthn handle this instead of having chaise do the redirect itself, because in some cases, having chaise do the redirect skips steps necessary to complete the logout.

For example, with globus_auth, what happens is that the redirect_path returned to chaise by webauthn is a URL that will send the user to a version of the Globus logout page with a link that the user can use to get back to the appropriate chaise page (the one that was originally specified by the `logout_url` parameter to `DELETE /session`, or the `default_logout_url` config parameter if no `logout_url` was specified).

**Comment by svoinea** [comment] 2016-06-02 22:31
Re-fixed in the commit 7af6c8797fd5b21f6aec615cdd1af8f79fbcd7dd.

The `chaise-config['logoutURL']` parameter is passed now in the `DELETE /session` request. The user will be redirected to the URL specified by the `redirect_url` field of the DELETE response, or to the `'/chaise/logout'` page if the DELETE response does not contain the `redirect_url` field.

**Comment by mikedarcy** [comment] 2016-06-07 20:27
This isn't working as expected for me.  

If I have a default specified in `ermrest_config.js`, then that value is always getting returned from the delete request as the logoutURL and the overrides I specify in `chaise-config.js` have no effect. I do not see the `redirect_url` field in the response -- maybe because I am only using session auth?  I also do not see anywhere in the logout handling code of chaise where the `redirect_url` variable is being checked/used.

On the other hand, I can now remove the default from `ermrest_config.js` and not get an error in chaise, so that is good.  The JSON result from webauthn contains a null logout_url value, as expected. The problem now is that the `submitLogout` function does not honor the `chaise-config['logoutURL']` override when the return value is null, but rather uses the hard-coded default of `/chaise/search`:

```js
var logout_url = (logout_uri != null ? logout_uri : '/chaise/logout');
```

I think this statement needs to be rewritten to first try the logout_uri variable returned by webauthn, then try the `chaise-config['logoutURL']` override variable, and then finally fall back on the hardcoded default.

**Comment by svoinea** [comment] 2016-06-07 22:17
To clarify what happens in Chaise:

 - If `chaise-config.js` contains the `logoutURL` parameter, then its value is passed to the `DELETE /ermrest/authn/session` request through the `logout_url` parameter (see `function deleteSession(param)` 
 - The `function successDeleteSession(data, textStatus, jqXHR, param)` parses the response and sends to the `submitLogout` function the `logout_url` field.

I can confirm that I tested those with globus_auth and it works as expected.

**Comment by mikedarcy** [comment] 2016-06-07 23:22
I understand how it works, I've been debugging it. What I thought I made clear was that it is not working as expected for my use case, which is different than what you tested...  

In the debugger I can see the `logout_url` parameter being correctly passed to the `DELETE` call, but that value is not what is returned in the response body.  What *is* returned is either the `default_logout_path` as configured in `ermrest_config.js` or NULL, if `default_logout_path` is missing from the config file.

I don't know if this is a problem with webauthn or not, but regardless, I think if Chaise gets back a NULL `logout_url` from the `DELETE /ermrest/authn/session` it should **not** fall back on the hard-coded default that is currently in the `submitLogout` function that I quoted above. Rather, it should  first try to use a `chaise-config['logoutURL']` and only if *that* is missing fall back on the hard-coded value.  

I think guarding against a NULL value here (and allowing the override) is a reasonable behavior, especially if `default_logout_path` is not a mandatory webauthn config parameter. I don't know whether it is mandatory or not. @ljpearlman?

Maybe you can try a few things and see if you can verify my issue:

1. Test with basic auth/session and not globus auth.
2. Don't include a  `default_logout_path` in your ermrest_config.json
3. Temporarily move your chaise install to a different webroot-relative directory (e.g. /var/www/html/chaise-test/), edit the `logoutURL` and `dataBrowser` parameters in `chaise-config.js` accordingly, and then test the logout flow.

**Comment by ljpearlman** [comment] 2016-06-08 03:09
This is what `DELETE /ermrest/authn/session` does (or, if it doesn't, that's a bug):

If the user is logged in:

- If `logout_url` is passed in the request arguments, then `logout_url` is set to that value in the response, which is sent with a 200 status.
- Otherwise, if `default_logout_url` is set in the webauthn configuration, then `logout_url` is set to that value in the response, which is sent with a 200 status
- Otherwise, webauthn raises `ConfigurationError("No logout URL specified or configured")` which results in a 500 error.

If the user isn't logged in:

- If `logout_no_session_path` is set in the webauthn configuration, then `logout_url` is set to that value in the response, which is sent with a 404 status.
- Otherwise, if `default_logout_url` is set in the webauthn configuration, then `logout_url` is set to that value in the response, which is sent with a 404 status.

So I think one of two things is happening here: either you were logged in and there's a bug, or you weren't and the "not logged in" code got exercised (if you still have logs, the arguments and return statuses should both be there).

I'm open to the suggestions for changes in the "not logged in" logic, if that's what's happening here. I'd originally logging out when you don't have a valid session as an error, but maybe we should consider it just something people do sometimes.

Either way, the correct behavior for Chaise is to honor `logout_url` if it's set and to present some reasonably nice-looking error popup to the user if it gets a 500 error (which I believe is what it's currently doing).

**Comment by mikedarcy** [comment] 2016-06-08 17:55
Looks like a bug in the webauthn database provider: https://github.com/informatics-isi-edu/webauthn/issues/40

I still think the chaise code should handle a possible Null return value here and support replacing with the override from the config rather than a hardcoded default.

**Comment by svoinea** [comment] 2016-06-08 18:26
In the case that `chaise-config.js` has no `logoutURL` parameter (meaning no `logout_url` parameter is passed to the `DELETE /ermrest/authn/session` request), and in the `ermrest_config.js` the `default_logout_path` is missing, what does the `DELETE /ermrest/authn/session` request return?

**Comment by mikedarcy** [comment] 2016-06-08 18:46
Im

**Comment by karlcz** [comment] 2016-06-08 18:48
Let me summarize what I think are the desired behaviors:

1. If chaise-config has a logoutURL setting, it will pass it in the logout_url parameter to the DELETE call. Otherwise it should omit this parameter in the request.
2. If webauthn receives a logout_url parameter, it will incorporate it into the response object. This MAY be a verbatim copy in the redirect URL or MAY embed the URL into another provider-specific redirect URL that also takes query parameters, etc. The expectation is that the end of the provider-specific flow will somehow allow the browser to return to the URL specified in the logout_url parameter. That return might require user action, i.e. if the final URL is made into a link on the provider-specific logout page.
3. The DELETE response object SHOULD be properly populated for both the 200 and 404 status responses.
4. If webauthn does not receive a logout_url parameter, it will consider the default logout URL configured in the webauthn config file instead. If this default is not configured, it will consider there to be no configured post-logout URL to return to after any provider-specific steps are completed. The browser MAY be left on a provider-specific page or the response object MAY have a null redirect URL if there were no provider-specific steps to follow either.
5. If there is any server-side or communication error, the response object MAY be entirely missing and/or have some other response status other than 200 or 404.

We seem to be having less agreement about what to do in the last two cases above:

- One suggestion is to get rid of hard-coded magic URLs. If you get to a successful post-logout with a null redirect URL, this means none was configured and perhaps the app should just continue and/or reload itself with this currently anonymous client state.  If people don't want that, they should configure chaise and/or webauthn differently, rather than relying on any hard-coded URL.
- As for the final failure case, I think it is another in the category of finite retry with backoff. What I don't know is whether we need yet another landing page to tell the user that their logout status is uncertain and that they may want to close their browser, delete cookies, etc. This would be needed if we reached our maximum retry limit and never got one of the successful 200 or 404 responses with a valid response object.

**Comment by ljpearlman** [comment] 2016-06-30 23:21
(closed this by accident earlier)

**Comment by ljpearlman** [comment] 2016-06-30 23:32
I'm not sure what the status of this bug is. I think the webauthn bits are done, but the last two paragraphs of @karlcz's most recent comment raise some questions about what chaise should be doing in a couple extreme failure cases.

(Assigning this to @hongsudt to figure out how to proceed).

**Comment by hongsudt** [comment] 2016-08-23 01:02
@mikedarcy is this still an issue? If not, please close the issue.

**Closed** 2016-08-23 01:56 UTC
Labels: enhancement
