### ISSUE TITLE
Errors uploading files with multi-add

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1749] opened 2019-03-28 19:42 UTC
An RBK user got this error when trying to add multiple records with file uploads (she hit "submit" a second time after the first failure). She was able to add a single record with no problems. You can test by selecting any specimen from https://dev.rebuildingakidney.org/chaise/recordset/#2/Gene_Expression:Specimen or https://staging.rebuildingakidney.org/chaise/recordset/#2/Gene_Expression:Specimen and clicking "Add" in the Images section. (I was able to successfully add two Image records at a time on rbk-dev, so it at least works some of the time).

![Capture-error2](https://user-images.githubusercontent.com/8785501/55187672-e145dc00-5156-11e9-94fa-f566ea141d15.JPG)

**Comment by jrchudy** [comment] 2019-03-28 23:57
Before each of the following tests I downloaded new czi files from random records on dev-rbk ranging from 50 mb up to 350 mb. I created 5 records each time with a different file uploaded for each record for each test. (I uploaded 15 distinct files across the 3 tests)

I tested with no network limit (~500 MBps upload, maybe 10 ms latency) and saw no issues. I waited maybe 1 minute for this to create the records before I saw the resultset view.

I tested with a normal network limit (~6 MBps upload, 300 ms latency) and saw no issues. I waited close to 5 minutes for this to create the records before I saw the resultset view.

I tested with a slow network limit (~2.5 MBps upload, 500 ms latency) and saw no issues. I waited close to 15 minutes for this to create the records before I saw the resultset view.

**Comment by hongsudt** [comment] 2019-03-29 00:55
More info from cris: 
Emily let me know in a different thread that she is using Windows 7 Enterprise and uses Firefox (52.0.1.0) and Chrome (73.0.3683.86).

**Comment by jrchudy** [comment] 2019-03-29 21:50
- could there be some race condition with the multi-add (i.e. somehow looking at the checksum result for the wrong record)?
   - **UPDATE**: this case is very unlikely. We make sure to create an individual upload job for each
- we need to be careful not to share something like a "file pointer/file descriptor" which has internal state such as current seek position, since different chunks cannot safely seek to a different offset to read the content they want to send
- when retrying a chunk, we have to remember to re-seek back to the beginning so we send the same data again (rather than whatever comes next after the chunk we already tried to send)
   - suspicion that chaise isn't handling the retry on chunks properly
   - The only retry that should continue would be if the attempt to cancel had a transient error and the cancel itself needs to be reissued
   - **UPDATE**: we create the set of chunks before any are sent to the server. Each chunk object keeps track of its start and end point in the original file. When retrying chunks, we are resending the same request object to the server again without going back into the code in `hatrac.js`. The retry logic is in `http.js` as a sort of interceptor
- the logs show an upload job created and then an attempt to finalize it w/o ever sending a chunk
    - chaise shouldn't try to finalize the upload job if it wasn't going to send data. it should have just deleted the job in that case (to leave the existing file).
   - chaise is issuing a "job finalization" request prematurely, before chunks have successfully completed
- see some sequences (in the logs) where many PUT chunk requests are getting a 404 response, I think because the job has already been cancelled by DELETE but then it keeps retrying chunks anyway
   - evidence that the job cancellation is buggy, with lots of useless chunk retry happening after the job was already cancelled
   - cancellation should be tracked on the client-side upload object 
   - all subsequent callbacks should check that state flag and avoid performing additional useless work on the dead upload

**Comment by hongsudt** [comment] 2019-04-01 18:46
RBK user in florida continues to have problems after the hatrac patch. 
![image](https://user-images.githubusercontent.com/414732/55351594-9dfbae00-5473-11e9-89a5-1b3923e09285.png)

**Comment by RFSH** [comment] 2019-04-02 17:07
I went over the code to figure out if there are any flaws in the current implementation of upload/hatrac.

We can summarize the whole logic of uploader as following:

1. Calculate checksum for all the files
2. Check whether files already exist on hatrac (and avoid uploading them)
3. Create upload job for all the files
4. Upload each file, chunk by chunk
5. Complete upload job for all the files

Apart from the first step, all the other steps are talking with server and therefore require some sort of flow-control. The first issue is that we're only utilizing flow-control for the 4th step. The other issue is that in this flow-control we're sending 10 chunks at a time, which seems like a high number and we might want to reduce it.

Also to keep track of the progress, we're just counting the number of chunks that are done (done means the request has been sent to the server, all the retries has been done, and server finally sent a successful response).  Which we might want to change this to a proper state management. So instead of counting, we should check which chunks are done. Because if a callback has been called twice, it might cause the count to be out of sync with the actual number of chunks (although based on my understanding of the code this doesn't seem to be the case).

**Comment by RFSH** [comment] 2019-04-03 00:33
I was able to produce the md5 missmatch error. Although this might not be the exact scenario that users faced the issue, but it's showing the same symptoms. This error is being thrown when user tries to upload several files that some of them already exist on the server. The mixture of new and existing files is causing this issue.

I was able to fix this bug by changing the logic of ending the 4th step (in the explained steps above) and starting the 5th step.

**Comment by jrchudy** [comment] 2019-04-03 01:02
Some background can be gathered from the following 2 queries. The first query surrounds the initial error occurrence, the second query surrounds the latest error occurrence. On March 28th (Thurs):
```
SELECT
  devicereportedtime,
  r_status,
  c_action, 
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('www.gudmap.org', 'www.rebuildingakidney.org')
  AND devicereportedtime > '2019-03-28 11:38:00'
  AND devicereportedtime < '2019-03-28 11:58:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Emily'
ORDER BY devicereportedtime, id;
```

This query (when run against `log2.isrd.isi.edu` on the `rsyslog` database) encompasses all log information surrounding the initial case that this error was reported for. 
> - The initial job she ran a couple days ago included 18 files to be uploaded (9 images and 9 thumbnails). During the initial check to see if the uploads exist already in hatrac, 2 of them returned a 200 code (already exist).
> - 16 upload jobs were created (the 2 files that already existed did not have jobs created). After 14 jobs had finished uploading all of their parts, the finalize was prematurely issued for 9 of the files (2 of the files that were included in this finalize were the 2 that already existed).
> - This premature firing of finalize caused some errors to start occurring while trying to upload chunks for the 15th file to upload. It caused an "upload/cancel" action to be sent to the server and all 3 files had a `DELETE` request issued against them which would cause the continual errors in the retry logic. A second set of finalize queries were sent, that had not been sent already, for the other 2 separate files where they failed with a 500 error then a 404 failure right after.

On April 1st (Mon):
```
SELECT
  devicereportedtime,
  r_status,
  c_action, 
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('www.gudmap.org', 'www.rebuildingakidney.org')
  AND devicereportedtime > '2019-04-01 11:05:00'
  AND devicereportedtime < '2019-04-01 11:15:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Emily'
ORDER BY devicereportedtime, id;
```
This query (when run against `log2.isrd.isi.edu` on the `rsyslog` database) encompasses all log information surrounding the latest case that this error was reported for. 
> - This job she ran yesterday included 6 files to be uploaded (3 images and 3 thumbnails). During the initial check to see if the uploads exist already in hatrac, 3 of them returned a 200 code (already exist). Those happened to be for each thumbnail. The thumbnails were so small they only took 1 chunk to upload.
> - 3 upload jobs were created (the 3 thumbnails that already existed did not have jobs created). After 2 jobs had finished uploading all of their parts, the finalize was prematurely issued for 1 of the files (the file included in this finalize was the file that had not been uploaded yet).
> - This premature firing of finalize caused some errors to start occurring while trying to upload chunks for the 3rd file. It caused an "upload/cancel" action to be sent to the server and all 3 files had a `DELETE` request issued against them which would cause the continual errors in the retry logic. A second set of finalize queries were sent, that had not been sent already, for the other 2 separate files where they failed with a 500 error then a 404 failure right after.

**Comment by jrchudy** [comment] 2019-04-03 21:24
On March 28th (Thurs):

```
SELECT
  devicereportedtime,
  r_status,
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('www.gudmap.org', 'www.rebuildingakidney.org')
  AND devicereportedtime > '2019-03-28 12:20:00'
  AND devicereportedtime < '2019-03-28 12:25:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Emily'
ORDER BY devicereportedtime, id;
```

> - This job, ran on thursday, included 4 files to be uploaded (2 images and 2 thumbnails). During the initial check to see if the uploads exist already in hatrac, 2 of them returned a 200 code (already exist).
> - 2 upload jobs were created (the 2 thumbnails that already existed did not have jobs created). After the first job finished uploading all of its parts, the finalize was prematurely issued for 1 of the files (the file in this finalize was the file that had not been uploaded yet).
> - This premature firing of finalize caused some errors to start occurring while trying to upload chunks for the 2nd file. It caused an "upload/cancel" action to be sent to the server and both files had a DELETE request issued against them which would cause the continual errors in the retry logic. A second finalize query was sent, the one that had not been sent yet, for the other file which failed with a 500 error then a 404 failure right after (presumably because it retried on the 500 error response).


On March 29th (Fri):

```
SELECT
  devicereportedtime,
  r_status,
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('www.gudmap.org', 'www.rebuildingakidney.org')
  AND devicereportedtime > '2019-03-29 06:10:00'
  AND devicereportedtime < '2019-03-29 06:15:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Emily'
ORDER BY devicereportedtime, id;
```
This failure is almost identical to the one above in this comment. It includes the same 2 files that are trying to be uploaded (non-thumbnails).

> - This job, ran on friday, included 4 files to be uploaded (2 images and 2 thumbnails). During the initial check to see if the uploads exist already in hatrac, 2 of them returned a 200 code (already exist).
> - 2 upload jobs were created (the 2 thumbnails that already existed did not have jobs created). After the first job finished uploading all of its parts, the finalize was prematurely issued for 1 of the files (the file in this finalize was the file that had not been uploaded yet).
> - This premature firing of finalize caused some errors to start occurring while trying to upload chunks for the 2nd file. It caused an "upload/cancel" action to be sent to the server and both files had a DELETE request issued against them which would cause the continual errors in the retry logic. A second finalize query was sent, the one that had not been sent yet, for the other file which failed with a 500 error then a 404 failure right after (presumably because it retried on the 500 error response).


On April 1st (Mon):

```
SELECT
  devicereportedtime,
  r_status,
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('www.gudmap.org', 'www.rebuildingakidney.org')
  AND devicereportedtime > '2019-04-01 10:59:00'
  AND devicereportedtime < '2019-04-01 11:05:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Emily'
ORDER BY devicereportedtime, id;
```

> - This job, ran on monday, included 6 files to be uploaded (3 images and 3 thumbnails). During the initial check to see if the uploads exist already in hatrac, 3 of them returned a 200 code (already exist).
> - 3 upload jobs were created (the 3 thumbnails that already existed did not have jobs created). After 2 jobs had finished uploading all of their parts, the finalize was prematurely issued for 1 of the files (the file included in this finalize was the file that had not been uploaded yet).
> - This premature firing of finalize caused some errors to start occurring while trying to upload chunks for the 3rd file. It caused an "upload/cancel" action to be sent to the server and all 3 files had a DELETE request issued against them which would cause the continual errors in the retry logic. A second set of finalize queries were sent, that had not been sent already, for the other 2 separate files where they failed with a 500 error then a 404 failure right after.

**Comment by jrchudy** [comment] 2019-04-04 00:46
From reproducing the bug today:
```
SELECT
  devicereportedtime,
  r_status,
  r_method,
  r_path
FROM derivarequests
WHERE fromhost IN ('staging.rebuildingakidney.org')
  AND devicereportedtime > '2019-04-03 14:44:00'
  AND devicereportedtime < '2019-04-03 14:45:00'
  AND syslogtag ~ '^hatrac'
  AND u_fname ~ 'Josh'
ORDER BY devicereportedtime, id;
```

I was trying to upload 3 files, 2 that already existed on the server and 1 new one. The new file had its job properly created, but it tried to finalize the file before any of its chunks were uploaded. This is because of the order that the code in chaise executes. This error only occurs when the file that doesn't exist yet is one of the last files to upload. 

The flaw in the count logic can be seen with this case because we know that the 1st 2 files shouldn't have an upload job being created. We also know in the code that we get to those callbacks and try to `finalize` all jobs before the last file has actually uploaded.

**Comment by RFSH** [comment] 2019-04-04 19:44
The changes to fix this issue are merged with master in both [ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/commit/bbd5f51b5de9b1ad4c5de9ea4659ce98c912d002) and [chaise](https://github.com/informatics-isi-edu/chaise/commit/603428aad64ca1f21d3ced3919f10f7918d37f9a).

The new #1753 issue has been created for more improvement regarding the uploader.

**Comment by RFSH** [comment] 2019-04-04 20:40
@ljpearlman @hongsudt I tested the same scenarios in rbk-dev with the new changes and everything seems to be working fine. We should be able to update the deployments and ask our user to try again.

**Comment by RFSH** [comment] 2019-07-25 17:11
I am going to close this issue due to inactivity. We should create a new issue if the bug still exists.

**Closed by RFSH** 2019-07-25 17:11 UTC
Labels: bug
