### ISSUE TITLE
Multi-select row disabled inconsistency

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1817] opened 2019-07-03 22:11 UTC
Starting from this [record page](https://staging.rebuildingakidney.org/chaise/record/#2/Common:Collection/RID=Q-3K5C):
 1. click the `Add` link for the `Specimen Collection` table. 
 2. In the modal dialog, open the facet panel, go to the `Specimen Collection` facet, and select the  `Histology of Human and Mouse embryonic and fetal kidney` option.
 3. Next, open the `Species` facet and select `Mus Musculus`
    - The table should have 25/33 records shown with the first one having `metanephros (TS18-TS28)` as the `Anatomical Sources` value. This row should be disabled
 4. Change the limit dropdown to be 50.
    - The order of the displayed data shouldn't change, but sometimes this first row (including `metanephros (...)`) is no longer disabled
    - if it is not disabled, it becomes selectable (Select All can select it) and submitting the data will cause an error to be thrown.
    - following these steps is how the error from [this issue](https://github.com/informatics-isi-edu/chaise/issues/1816) was caused

**Comment by RFSH** [comment] 2019-07-09 01:19
After clicking on `Add` link for the `Specimen Collection` table, we're generating two requests

R1: A page of `Specimen` that we are going to show to the users.

R2: All the `Specimen` that have a `Collection` with the given `RID=Q-3K5C`, and have the same sorting and paging as the R1 request.

We show the result of R1, and use R2 to disable the existing values. This only works if R2 is a subset of R1 request. Which means that it has the same sorting and paging settings of the R1, alongside the same facets. The issue is that the function that I wrote for this feature [doesn't support facets](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/reference.js#L2330). So if you change the facets for getting R1, the R2 won't be the subset of R1 anymore.

I am going to change that function to support facets.

**Comment by RFSH** [comment] 2019-07-11 16:13
@ljpearlman @hongsudt I've pushed a fix for this to ermrestjs. Link to the commit:
https://github.com/informatics-isi-edu/ermrestjs/commit/cc2f8bc340a5b4e1b1394580dd0137f7395c474a

Can you please verify that this has solved the issue?

**Comment by RFSH** [comment] 2019-07-25 17:10
I am going to close this issue due to inactivity. We should create a new issue if the bug still exists.

**Closed by RFSH** 2019-07-25 17:10 UTC
Labels: bug, record
