### ISSUE TITLE
npm and build scripts

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1945] opened 2020-05-05 04:47 UTC
I tried to upgrade rbk-dev to Fedora 31, and the installation script (`firstboot.d/50-software-install.sh`) failed when trying to install chaise:

```
node_modules/.bin/node-sass --style=compressed --source-map-embed common/styles/scss/app.scss common/styles/app.css
/home/isrddev/chaise/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/isrddev/chaise/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/isrddev/chaise/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/isrddev/chaise/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/isrddev/chaise/node_modules/node-sass/bin/node-sass:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
make: *** [Makefile:575: common/styles/app.css] Error 1
firstboot.d/50-software-install.sh error: "Command (make install) returned non-zero status=2"
```

I ran `npm rebuild node-sass` (as isrddev in ~isrddev/chaise) and was able to run the install script and the rest of the firstboot scripts by hand (except for a jekyll issue building the static website, but I think that's probably unrelated).

I don't know what the solution is here -- would it make sense to add `npm rebuild node-sass` to the chaise Makefile, or to specify an npm version number to `npm install` or `npm update`?

**Comment by ljpearlman** [comment] 2020-05-05 05:00
P.S. I'm a little mystified because the synapse-dev recipe doesn't appear to treat npm any differently from the rbk-dev recipe. Looking at the kickstart logs, though, the initial npm installation on synapse-dev was an earlier version than on rbk-dev, so maybe that's the difference.

**Comment by karlcz** [comment] 2020-05-05 16:08
I think we've run into this elsewhere and it got fixed by manual
intervention.  It is hard enough to then go back to reproduce that I
don't think we have a real recipe fix yet.

There are 'make distclean' targets for chaise and ermrestjs which
clean up the build dir state to a safer state for rebuild.  I think
that will cover the problem you found too.  I think we might need
to add that to all the full-rebuild recipe steps somehow, but at the
same time they don't think it should happen on every hourly rebuild
since it blows away a bunch of build cache stuff.

karl

**Comment by RFSH** [comment] 2020-05-05 18:14
Yes, I created this issue when this came up before: 
https://github.com/informatics-isi-edu/chaise/issues/1892#issuecomment-591642142

**Comment by ljpearlman** [comment] 2020-05-05 19:17
Any objections to me changing the "make install" in chaise_install to
```
make install || (make distclean; make install)
```
(I never know where to put the question mark when I ask a question in this format).

**Closed** 2020-08-06 17:29 UTC
