### ISSUE TITLE
Asset upload md5 mismatch error

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1363] opened 2017-11-08 19:24 UTC
We have a user that has encountered this error now a few times. They are on a Mac running Chrome. The network speed they say is not terribly slow.

![image](https://user-images.githubusercontent.com/4202842/32569856-3cd16d46-c477-11e7-8744-b2dd3818474e.png)

I searched for the strings in this error message in chaise and ermrestjs repos but did not find a hit. I need someone to point me in the right direction so I can do more to debug this.

**Comment by karlcz** [comment] 2017-11-09 18:11
Is it repeatable or sporadic? If repeatable for the user with the same file, I'd be concerned about possible browser-based corruption due to some unexpected character encoding translation or other non-binary file content handling.

If it's sporadic even for that user and the same test file, I'd be concerned about a race condition where the chunked upload job isn't getting all of its chunks sent before it attempts to finalize the upload job.

Since we're running over HTTPS, it seems highly unlikely that a corrupt packet on the wire would make it through the crypto stack and hit us with this end-to-end check.

**Comment by hongsudt** [comment] 2018-03-01 20:54
@robes do we still have this problem?

**Comment by robes** [comment] 2018-03-01 21:45
I missed Karl's comment from before. It is 'sporadic'.

I can ask this user but I would expect this is still a problem.

**Comment by robes** [comment] 2018-03-01 23:17
User got back to me and says "everything is working properly now."

**Comment by hongsudt** [comment] 2018-03-01 23:28
Can I close this issue?

**Comment by hongsudt** [comment] 2018-04-24 18:58
@jrchudy let's document this issue on what we have done and then close it..

**Comment by jrchudy** [comment] 2018-04-24 19:41
This issue is a duplicate of an issue in `ermrestJS`.

https://github.com/informatics-isi-edu/ermrestjs/issues/554

**Closed by jrchudy** 2018-04-24 19:41 UTC
Labels: bug, recordedit
