### ISSUE TITLE
Recordedit submit gives no indication of progress

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1078] opened 2017-04-21 21:52 UTC
I ran across this by chance. The server was in generally responding very slowing based on general page loads and record app loads etc.

Then I went to edit a record to add 3 entities (these were small 'pure' binary associations). Clicking on submit the app gives no indicate that anything is happening. Click, click, click... no sign of anything happening.

Then I closed the record edit and went back to the record page and went to retry adding. This time I just did one and got a 409 conflict error, because the associative entity had been added.

Just like any other network activity that blocks actions, we should throw up the whole page spinner as soon as the user hits the 'Submit' button.

**Comment by jrchudy** [comment] 2017-04-21 21:59
This is a duplicate of issue #869.

**Closed by jrchudy** 2017-04-21 21:59 UTC
Labels: bug, recordedit
