### ISSUE TITLE
The view for related records shows the "Loading..." text.

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1067] opened 2017-04-18 21:14 UTC
The bug is present on `cirm-dev.isrd.isi.edu` for the `specimen_comments` table.
The URL is https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:specimen_comments/ID=219 
or equivalent, follow the steps:

1. From the `Search` menu, select `Specimen`.
2. Select the first specimen.
3. From the `Comments` related table, click the `View` icon.

The `Loading...` text is not present on `cirm-staging.isrd.isi.edu` which has the versions from `2017/02/03`.

I'm attaching the screenshot:

![comment_view](https://cloud.githubusercontent.com/assets/1609577/25153299/ee6259a8-2440-11e7-86b9-6169b905ee89.png)

**Comment by jrchudy** [comment] 2017-04-18 21:21
This is a duplicate of issue #1056.

**Closed** 2017-04-20 17:27 UTC
Labels: bug
