### ISSUE TITLE
Change over to standalone authn API outside ERMrest

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#298] opened 2016-04-21 17:58 UTC
The `/ermrest/authn/` API will change to `/authn/` after other work in this epic is completed.
If the authn API path is made configurable in chaise_config.js, this work could be done in advance and we simply change the deployed config when ready...

**Comment by hongsudt** [comment] 2016-06-08 01:34
@karlcz is this ready to be changed?

**Comment by karlcz** [comment] 2016-07-13 02:10
@hongsudt   The `/authn/` API on dev-isrd is working now, so someone can start working on making Chaise talk to it instead of `/ermrest/authn/`...

**Comment by karlcz** [comment] 2016-07-22 17:33
Can we schedule this small task soon?

**Comment by karlcz** [comment] 2016-11-10 21:19
I think we should get this going in master soon and coordinate with transitioning of VMs to Fedora-based recipes so that the new VMs are using the new `/authn/` API, in anticipation of eventually using the other mod_webauthn features and disabling the legacy copy of webauthn nested as `/ermrest/authn/`

**Comment by hongsudt** [comment] 2016-12-05 22:00
@karlcz  Is #822 a duplicate of this issue?

**Comment by karlcz** [comment] 2016-12-05 22:11
yes, I think #822 is a duplicate

**Comment by karlcz** [comment] 2016-12-05 22:14
Should #258 be handled at the same time?  Is this touching the same code?

**Closed** 2017-02-28 22:34 UTC
