### ISSUE TITLE
Error Handling in apps for Synchronous calls

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#945] opened 2017-01-23 19:27 UTC
Our Chaise apps need to have `try/catch` handling around the synchronous calls to `ermrestJS`. This is most noticeable in our functions that are used for on click handlers and for generating links.

**Comment by hongsudt** [comment] 2017-03-03 23:39
duplicate of #1012. I am closing this issue.

**Closed by hongsudt** 2017-03-03 23:39 UTC
Labels: record 2, recordedit, recordset
