### ISSUE TITLE
editing file_uri doesn't update the associated metadata

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1137] opened 2017-06-01 00:43 UTC
When a different file is uploaded, only the url get updated, not the md5, filename and filesize. 

I am not sure whether this is ermrestjs or chaise though.

**Comment by jrchudy** [comment] 2017-06-03 02:44
Closing this issue as a duplicate of issue #1132.

**Closed by jrchudy** 2017-06-03 02:44 UTC
Labels: bug, recordedit
