### ISSUE TITLE
Edit/Create should be disabled for versioned catalogs

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1727] opened 2019-02-21 20:40 UTC
When a user is viewing a versioned catalog, the edit and create options should not be available. If the user does navigate to the `recordedit` app somehow still, we should have a proper error message.

Current scenario allows for users to navigate to the `recordedit` page for both `create` and `edit`, but they are presented the following error on form submission.
`403 Forbidden The requested modification to catalog at previous revision is forbidden.`

**Comment by karlcz** [comment] 2019-02-21 21:20
Why isn't the app showing the error immediately due to the `rights` in the model not including insert/update permissions?  I don't see why it should ever offer the data-entry forms nor submit button.

Please confirm that the app is actually starting with the correct catalog model for the URL, i.e. if you are at `1@2R4-P12J-9V08` then you should also be using the schema from `/ermrest/catalog/1@2R4-P12J-9V08/schema` and considering the rights summary in that version of the model.

**Comment by jrchudy** [comment] 2019-02-21 22:21
When I go to rbk, I see `2R4-PHS4-ZTV2` as the catalog number when I look at this [rest API](https://dev.rebuildingakidney.org/ermrest/catalog/2). When I change to that catalog, I don't see anything different with the permissions on the catalog, schema, or tables. 

I tested this on the [Protocol:Subject](https://dev.rebuildingakidney.org/chaise/recordset/#2@2R4-PHS4-ZTV2/Protocol:Subject@sort(Term)) table.

**Comment by karlcz** [comment] 2019-02-22 19:24
OK, I reproduced this as well.  I've opened informatics-isi-edu/ermrest#217

**Comment by karlcz** [comment] 2019-02-22 21:57
The ermrest bug was fixed in master and py3 branches.  The fix has already rolled out to synapse-dev and other test VMs with hourly updates...

**Comment by karlcz** [comment] 2019-02-27 19:30
I verified that the Edit/Delete buttons go away now with a properly updated ermrest.

However, the Copy button also disappears.  This might frustrate someone who is trying to use historical data as the starting point for a new record?

**Comment by karlcz** [comment] 2019-03-06 19:18
I see you created a separate issue #1735 for the copy button.

**Closed by karlcz** 2019-03-06 19:18 UTC
Labels: recordedit
