### ISSUE TITLE
Recordset keeps refreshing content whenever you focus on the window

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#845] opened 2016-12-08 20:30 UTC
This issue is because of the [$window.onfocus](https://github.com/informatics-isi-edu/chaise/pull/824/files#diff-73795a03f41089eca884f8b6e0fb96b7R151) event handling for record add. We need to disable the event handling for recordset page.

To test it you can visit any recordset page and change your tab and come back to the recordset page again. The content gets refreshed. You can also try clicking the paging button, which again refreshes the content.

**Comment by hongsudt** [comment] 2016-12-15 01:33
@shinyichen Will this problem be addressed by your latest pull request?

**Comment by hongsudt** [comment] 2016-12-15 19:15
This is a duplicate of #831

**Closed by hongsudt** 2016-12-15 19:15 UTC
Labels: bug, recordset
