### ISSUE TITLE
change code to extract user name with the new web_authn

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#229] opened 2016-03-04 23:11 UTC
There are two parts
- [x] Update common header showing logged in user identity next to Logout button
- [x] Update viewer app where the ownership of annotations and comments is stored in ERMrest and displayed in the GUI. Move this item to informatics-isi-edu/rbk-project#95 ?

~~These changes should be made with runtime detection of the old or new-style webauthn session resource content in the `client` field, so that we can update the Chaise code on a server first, and have it continue to work with the older security but also immediately work once we switch a server to the new security.~~  We can just target the *new* security model and roll out this code at the same time as the security switchover.

**Comment by howdyjessie** [comment] 2016-03-04 23:14
@hongsudt To clarify: You want RBK to have a header with the username like in the Chaise Search app?

**Comment by karlcz** [comment] 2016-03-04 23:18
Later during this sprint, the response content of `GET /ermrest/authn/session` is going to change and all of our GUI apps that display it are going to require adjustment.  I think that's what this issue is meant to track.

**Comment by howdyjessie** [comment] 2016-03-04 23:25
@hongsudt @karlcz Ah my bad, I jumped the gun.

**Comment by karlcz** [comment] 2016-03-19 17:35
This issue is now ready to work on.  The isrd-dev VM has the new security enabled and you can login and see that the username display is now broken in chaise/search etc.  To make for an easier transition, the code should test at runtime whether the session response has a string or an object in the `client` field. If it is a string, that's old webauthn and the old display behavior works.  If it is an object that's the new webauthn and  I think it should use the `display_name` field of that object.

**Comment by karlcz** [comment] 2016-03-30 23:43
I think work on this issue can start with some caveats.  The `client` field of the `/ermrest/authn/session` resource is now an object and the previous string value is in the `id` field of that object.  This is the value that needs to be stored to implement real ownership decisions on a table row.

With a future change to the server, the `display_name` field will be important to display in the UI and to save somewhere in the table row as well.  The actual client `id` values will become much more opaque GUIDs similar to today's group IDs.

**Comment by ljpearlman** [comment] 2016-03-31 00:05
The client field has `id` (always) and `display_name` (generally the username the user typed to log in), `full_name`, and `email` where available, so you can start using them. These are all typically set, but it's always going to be possible that we'll be missing display_name, full_name, or email for a user. So you should test for each one and have some plan for dealing with its absence (which could just be not displaying it, or displaying one of the other fields).

**Comment by karlcz** [comment] 2016-03-31 00:29
@ljpearlman @robes @howdyjessie I guess if all these values may be sparsely populated, we should  change the author column in RBK tables to store a JSON blob containing the whole session.client field including whatever sparse values are available? I'd actually use the `jsonb` type in Postgres if we go this way...

**Comment by robes** [comment] 2016-03-31 00:50
makes sense to me.

**Comment by ljpearlman** [comment] 2016-03-31 00:57
The user table in the webauthn schema (in the branch) has columns for all these values. I'd be happier if we could use those instead of duplicating the information everywhere. I know it's different databases, but maybe we could use postgres's foreign db functionality and set up views that way.

I don't feel *that* strongly about it; I just hate having multiple copies of the same data.

**Comment by karlcz** [comment] 2016-04-06 00:21
@ljpearlman I don't think we want to add the complexity of FDWs right now. Also, I think this author column is more like provenance and so it is OK to denormalize the author info at time of row insertion. At least that's how I will sleep at night after we do this... :-)

**Comment by robes** [comment] 2016-04-06 00:43
+1  That’s how I was thinking of it too — as provenance related data.

On 4/5/16, 5:21 PM, "Karl Czajkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:

Also, I think this author column is more like provenance and so it is OK to denormalize the author info at time of row insertion.

**Comment by jrchudy** [comment] 2016-04-12 16:58
Looking at the session response object, the client object does indeed have a display_name, a full_name, and an email. The display_name is the globus username, *@globus.org (at least for my user), and full name looks like it's the full name set in globus.

Do we want to prioritize showing the full_name field before display_name or stay with the priority of display_name, full_name, then email?

**Comment by karlcz** [comment] 2016-04-12 17:05
Yes I think display_name comes first.  It shows *how* you logged in (via which provider) in a way that may be significant with all the weird account-linking variations we've seen.

I even wonder if email should be preferred over full name, but I guess either of them can be poorly correlated with the login identity provider that was chosen.  @ljpearlman ?

**Comment by ljpearlman** [comment] 2016-04-14 22:50
`display_name` doesn't always show how the user logged in; it shows the username provided by the provider. The globus_auth provider always returns information (which gets saved by webauthn as `id`, `display_name`, `email`, and `full_name`) associated with the user's _primary_ globus_auth username, regardless of how they authenticated.

If the issue is what to show as provenance information, where users will be looking at information about people other than themselves, I can't think of a good answer. People may not want their email addresses to be publicly available, so in a deployment where annotations, etc., are world-readable, email probably isn't a good choice. And for some providers, `display_name` will be the same as the email address. So that only leaves `full_name`--but as @karlcz pointed out, of all the fields we have, that's the least likely to be unique.

**Comment by jrchudy** [comment] 2016-04-14 22:50
I have completed the development for this issue. Assigning to @svoinea for review.

I did some preliminary testing on rbk dev with my globus account as a curator and used a globus testing account as a user and annotator. I verified everything that @carlkesselman laid out in issue [#69](https://github.com/informatics-isi-edu/rbk-project/issues/69).

**Comment by svoinea** [comment] 2016-04-26 23:00
Reviewed and works as expected.

**Closed by svoinea** 2016-04-26 23:00 UTC
