### ISSUE TITLE
confirmation page for recordset looks broken/unfinished after multi-record insert

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1987] opened 2020-07-27 23:09 UTC
...at least in some circumstances perhaps due to the use of pseudo-columns in the `compact` context of the table on which the insert is being performed. But this is far from a "corner" case as many of our useful tables are annotated to include pseudo-columns.

<img width="1903" alt="Screen Shot 2020-07-27 at 3 26 57 PM" src="https://user-images.githubusercontent.com/4202842/88600336-d806a100-d022-11ea-8712-fa9d72597f45.png">

In the above example, the 
- columns "Experiment Type" and "Protocol" are outbound foreign key references to denormalize the user readable "name" or "title" of the referenced entity -- they remain _blank_ even though "Experiment Type" had been selected (Protocol had not been)
- columns "Species" through "Genotype" are pseudo-columns that make two outbound foreign key references to get to the user readable "name" for the corresponding terms -- at least "Species" should have a value (in the reference table) but all 4 of these columns remain _blank_ *and* have _infinite spinners_
- "Local Id" may be ignored as it was a regular column that was left blank.

**Comment by RFSH** [comment] 2020-10-06 21:29
This is a duplicate of the newly created #2017 issue. Since the newer one has more information I am going to close this one.

**Closed by RFSH** 2020-10-06 21:29 UTC
