### ISSUE TITLE
403 error popup should be handled more gracefully

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#280] opened 2016-04-08 21:32 UTC
When the user logs in and has invalid permissions, a 403 error is displayed in a dialog box when the user navigates to `https://dev.rebuildingakidney.org/chaise/search/`. After closing the dialog box, the search page continues to spin the loading wheel as if something is going on in the background.

![image](https://cloud.githubusercontent.com/assets/2932600/14398109/7aef4e6c-fd96-11e5-820a-11c89c5e0f1b.png)

@robes suggested that this be handled more gracefully instead of popping up a notification to the user.

**Comment by svoinea** [comment] 2016-04-19 21:11
I'm closing it as this is a duplicate of #250

**Closed by svoinea** 2016-04-19 21:11 UTC
