### ISSUE TITLE
Back button on facet value pane is kind of funny...

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#118] opened 2015-10-08 20:27 UTC
You get the mouse changing when over the text, like its clickable, yet the text doesn't seem to be active.  You still have to go over to the arrow to move back.

**Comment by crisaless** [comment] 2015-10-08 21:14
Duplicate of #118

**Comment by crisaless** [comment] 2015-10-08 23:36
Carl, my github notifications were going into junk for a while so this skipped my notice. I reflexively closed it today during the staff meeting because I thought it was a duplicate but notice that you posted it today. I thought this was fixed (how the hover area isn't clickable, just a small area). I'll investigate this again - but can you try again with the cache cleared just to make sure?

**Comment by carlkesselman** [comment] 2015-10-09 03:42
Yep, still seeing it.  Mouse turns into different cursor when over the text part of the attribute name, but clicking doesn’t do anything.  Only works when I move over the the back arrow.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 8, 2015, at 4:36 PM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


Carl, my github notifications were going into junk for a while so this skipped my notice. I reflexively closed it today during the staff meeting because I thought it was a duplicate but notice that you posted it today. I thought this was fixed (how the hover area isn't clickable, just a small area). I'll investigate this again - but can you try again with the cache cleared just to make sure?

**Comment by crisaless** [comment] 2015-10-09 16:26
I misunderstood. I only targeted the back arrow itself. In order to make the whole 'row' active, that'll require more tinkering. Serban has used AngularJS for that in other places, so I'll give that a try.

**Comment by carlkesselman** [comment] 2015-10-09 16:29
Ok.  The problem is we are sending a mixed message.  Mouse curser changes, but there is no action attached.  So we should either make text clickable (probably the right thing to do), or have the mouse curser not change.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 9, 2015, at 9:26 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


I misunderstood. I only targeted the back arrow itself. In order to make the whole 'row' active, that'll require more tinkering. Serban has used AngularJS for that in other places, so I'll give that a try.

**Comment by crisaless** [comment] 2015-10-09 17:11
Committed a fix to make the entire header there clickable. I also made the title the same blue color as the arrow to show that it's clickable. Should show up on the next deployment update

**Comment by howdyjessie** [comment] 2015-10-09 17:41
Because of how close the back arrow and title are together, when we make the back arrow and the title the same blue color, this can indicate that clicking on this target will take you back to <whatever the title is> instead of just taking you back one pane. 

If the size of the back arrow target is ok as it was, wouldn't it be better to just make the cursor not make the Mickey Mouse hand when hovering over the title?

**Comment by crisaless** [comment] 2015-10-09 17:54
I don't think it make sense that it'll take you back to [title] because you're already there. But I see what you mean. The title doesn't equal 'Back', just the arrow. Reverting it the way it was and taking out the pointer behavior is trivial. But it is nice to have a large hover and click target like it is now. It may not be kosher, but maybe making the title black, while still giving it the click behavior, may split the difference. So it would behave the new way, but just the arrow would be blue and the title itself black. What do you think @carlkesselman ?

**Comment by robes** [comment] 2015-10-09 17:58
+1 for me. (keep the label black, but make it a click target to go back, while just the arrow is blue)


________________________________

**Comment by carlkesselman** [comment] 2015-10-09 17:59
I think we should err on the side of having a big clickable area.  I’m a bit less concerned about the color and more concerned about the pointer.  So if the pointer changes shape, it should be clickable.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 9, 2015, at 10:54 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think it make sense that it'll take you back to [title] because you're already there. But I see what you mean. The title doesn't equal 'Back', just the arrow. Reverting it the way it was and taking out the pointer behavior is trivial. But it is nice to have a large hover and click target like it is now. It may not be kosher, but maybe making the title black, while still giving it the click behavior, may split the difference. So it would behave the new way, but just the arrow would be blue and the title itself black. What do you think @carlkesselman<https://github.com/carlkesselman> ?

**Comment by howdyjessie** [comment] 2015-10-09 18:06
+1 for "(keep the label black, but make it a click target to go back, while just the arrow is blue)" too

**Closed** 2015-10-22 23:11 UTC
Labels: bug
