### ISSUE TITLE
Support array column type in recordedit

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1408] opened 2017-12-13 19:51 UTC
The array column type's contents can only be values of scalar types.

In the `recordedit` form, need to support the following functionality:
 - adding more cells for the array
 - removing cells from the array
 - reordering the data in the array
 - edit any one of the cells

This issue is currently relying on [this PR](https://github.com/informatics-isi-edu/ermrestjs/pull/566) in `ermrestJS`. It adds more functionality for tinkering with the display of array columns.

NOTE: 
 - No array of type `markdown`.
 - This allows for a third level of types to be defined. (domain type that is of type array that has scalar types inside)

**Comment by amitjha21** [comment] 2018-02-22 23:16
As per today's discussion, 4 different cases pertaining to base type and domain type.

No. | isArray | isDomain | Typename | Base type
------- | ------- | ------- | -------| -------
1| False | False | Text|
2| False | True | Markdown| 1
3| True | False | Text [ ] |1
4| False | True | "Tex" |3

**Comment by RFSH** [comment] 2018-05-02 18:27
I created an issue for the changes that we need to have basic array support in the read-only modes.

**Comment by jrchudy** [comment] 2018-06-01 23:59
- [ ] Types that have yet to be implemented and tested fully:
 - float
 - date
 - timestamp
- [ ] Test cases are very minimal and need to be extended to each of these types.
- [ ] presentation bug when a new cell is added, it duplicates column header.
- [ ] HTML changes (needs more information)

**Comment by hongsudt** [comment] 2018-11-07 19:31
A simple array support that shouldn't take a lot of time is to provide a adjustable text box and validate to make sure that it follows the json array syntax.

**Comment by RFSH** [comment] 2018-12-21 00:18
#### Required features and How it should behave
- Chaise should detect array columns. You can do this check by looking at the `Column.type.isArray` attribute.
- When there's no existing data (in create or edit mode), we should show one input alongside two buttons. One for adding new input and one for removing the existing input (each input should have the remove button beside it). The latter should be disabled if there's just one input showing. The ordering of inputs matter too. I don't think this is in the requirements but we might want to add a way to change the ordering of inputs. There are some directives that might give you all these features.
- When there's an existing value we should put each of the array values into different inputs.
- Having just one input that is empty should be translated into `null` value instead of an array of `null` ([`null`]).
- If there are more than one inputs, we should treat the empty ones as null value. So for example if there are two inputs and the first one is empty and the second one has a value of "test". We should send a `[null, "test"]` to ermrestjs.

#### How to create array column
Some examples of array column can be found [here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/test/specs/common/conf/common_schema_2/schema.json#L125). You can create your own schema with some array columns.

#### Guideline and code changes
Before jumping into the code I think it's better if you just take a quick look at how the recordedit is written. It's our most complicated app, so just take a look at the existing code before jumping into the code. Since I'm not very fluent with chaise code, I did the same and the following steps are what I think would be the best way to approach this. You don't need to completely follow them. It's just a guideline. I might have missed some steps.

- Add a new `inputType` that [this function](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/recordedit.utils.js#L8) is going to return. Then the appropriate inputType will be attached to the `columnModel` in [here](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/recordEdit.app.js#L252).

- Add a new type of input [here](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/index.html.in#L235) that will be used when the inputType is what you defined in the last step. It might be better if you create your own directive for array inputs, I'm not sure. At this point you might want to focus more on the UI and make sure all the components are working properly. Then you can work on actually integrating it with recordedit.

- You most probably should reuse the [`input-switch` directive](https://github.com/informatics-isi-edu/chaise/blob/master/common/inputs.js#L360). It will create appropriate type of input based on its type. It's currently only used for the "select-all" feature. But eventually we might want to refactor the existing input types in recordedit to use that. You most probably need to adjust input-switch too and add the array columns in there. We want the select-all feature for array columns too. It might be easier to ignore adding select-all feature to arrays for now. I'm not sure, you might have to think more about this.

- Your array input directive should handle adding multiple inputs itself. You might be able to have all the logic of handling the array value types in there without involving any of the existing recordedit code. For example in the `form.controller.js` in different places we are transforming the value based on its type. If your directive does these sort of logic by itself, then you don't need to worry about changing the existing code. And the existing code can just treat that input like an ordinary input (there won't be any transformation and it will just copy the data. The actual transformation should happen in your array input directive alone).

Again as I mentioned earlier these are just guidelines. If they're not helpful to you, you can ignore them.

**Comment by RFSH** [comment] 2019-02-12 19:29
A minimal and temporary solution for having arrays in recordedit is treating them the same way as `json` columns. Achieving this with the current implementation is simple, we just have to make sure we're mapping array columns to `json` inputs ([Here](https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L1079) and [here](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L89)).

If we just do this simple change, then we can at least support arrays. Although we have to rely on ermrest to do the validation of values. The following is the error message that we currently show when a user tries to submit `["test", 1]` for an `int4[]` column:

```
Error 400 Bad Request The request is malformed. Bad JSON array input. ERROR: invalid input syntax for integer: "test"
```

@hongsudt Is this message clear enough? Should we just do this simple change? or should we spend more time to have a proper value validation here? If we are going to implement the complete support for arrays, the extra code that we have to add for validation now won't be useful.

**Comment by hongsudt** [comment] 2019-02-13 19:57
We should this get this minimal change in place, so that Facebase can start using it (with training on a small group of user). 

However, this error message is very hard to understand.. And if there are multiple array columns, there is no way for me to even know where to address the issue. So I think we should do simple client-side validation if simple or just wait and put the GUI in place.

**Comment by RFSH** [comment] 2019-02-23 00:47
The changes for a simple array support has been merged into master. Chaise is going to provide a textarea for array columns which is similar to what we provide for json columns. You have to write the literal string value of the array ( `["value1", "value2"]` with brackets and double quotes) in the textarea. We’ve added a customized placeholder for these inputs to help the users. It also has its own special validators to validate the array structure and each individual values in the array.

**Comment by ladukaraniket** [comment] 2023-06-27 20:44
@hongsudt, @jrchudy and @RFSH ,
I have explored the following 3 approaches to implement the list - 


## Using the library `react-beautiful-dnd`
- It is a lightweight library which allows us to implement drag and drop functionality quite easily.
- The amount of code to be written is minimal and easy to read and understand.
- Can support up to 10,000 items @ 60fps with virtual lists and comes with visually appealing animations
- easy to detect ordering of items in terms of index. Easy to get the output in a required format.
- dependencies - `@babel/runtime, css-box-model, memoize-one, raf-schd, react-redux, redux, use-memo-one`
- [Entire list of dependencies](https://www.npmjs.com/package/react-beautiful-dnd?activeTab=dependencies)



> ![react-b-dnd](https://github.com/informatics-isi-edu/chaise/assets/44138408/3c17cea6-9b22-4d94-89fa-5f97b18ae116)


<hr>


## Using `javascript`
- very lightweight and fast.
- custom logic required to detect row position and rearrange the item once it is dragged.
- no animations. animations will have to be added if required.
- All the edge cases will have to be checked and covered to mitigate unexpected behavior.

> ![js](https://github.com/informatics-isi-edu/chaise/assets/44138408/88e574dc-18e2-4c32-946b-c02517943a72)


<hr>


## Using the library `react-draggable`
- lightweight as compared to react-beautiful-dnd.
- makes items draggable anywhere across the screen.
- the behavior is similar to moving widgets or windows on a screen.
- custom logic required to restrict the movement of items within a set area and also prevent items from overlapping.
- custom logic required to detect row position and rearrange the item once it is dragged.

> ![react-draggable](https://github.com/informatics-isi-edu/chaise/assets/44138408/48665fd4-9e2e-419f-9af3-333e06790184)

**Comment by carlkesselman** [comment] 2023-06-27 21:13
probably out of scope.. but it would be cool if this worked on facets and then we updated the annotations…..

On Jun 27, 2023, at 1:44 PM, Aniket Ladukar ***@***.***> wrote:



@hongsudt<https://urldefense.us/v2/url?u=https-3A__github.com_hongsudt&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=zGFtYCdPtz0wBXjoU3wvNWpUeEjCERBFHq_8Fd1-rVc&e=>, @jrchudy<https://urldefense.us/v2/url?u=https-3A__github.com_jrchudy&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=By3So_QM8qhrLhIIn2kaDBZ6miC7wQZpouVU97ibSrU&e=> and @RFSH<https://urldefense.us/v2/url?u=https-3A__github.com_RFSH&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=pPpFDurOp6MQnnnXV1j4IqqOgifm6EyVrbs_L4OVugk&e=> ,
I have explored the following 3 approaches to implement the list -

Using the library react-beautiful-dnd

  *   It is a lightweight library which allows us to implement drag and drop functionality quite easily.
  *   The amount of code to be written is minimal and easy to read and understand.
  *   Can support up to 10,000 items @ 60fps with virtual lists and comes with visually appealing animations
  *   easy to detect ordering of items in terms of index. Easy to get the output in a required format.
  *   dependencies - @babel/runtime, css-box-model, memoize-one, raf-schd, react-redux, redux, use-memo-one
  *   Entire list of dependencies<https://urldefense.us/v2/url?u=https-3A__www.npmjs.com_package_react-2Dbeautiful-2Ddnd-3FactiveTab-3Ddependencies&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=VqJD1HmXt6sNoGkdxweGe-Hlrz-EOSpN3dyQmPoqZJQ&e=>

[react-b-dnd]<https://urldefense.us/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_44138408_249274107-2D3c17cea6-2D9b22-2D4d94-2D89fa-2D5f97b18ae116.gif&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=o0cFbif7jVIaC0j0CDH_KPXtO5ugxWRXtR7u1zDKKX8&e=>

________________________________
Using javascript

  *   very lightweight and fast.
  *   custom logic required to detect row position and rearrange the item once it is dragged.
  *   no animations. animations will have to be added if required.
  *   All the edge cases will have to be checked and covered to mitigate unexpected behavior.

[js]<https://urldefense.us/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_44138408_249276422-2D88e574dc-2D18e2-2D4c32-2D946b-2Dc02517943a72.gif&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=hiO1NNCupPcL1cDNP4ytenJKgKXn0N5WtqE5CbLeE0Y&e=>

________________________________
Using the library react-draggable

  *   lightweight as compared to react-beautiful-dnd.
  *   makes items draggable anywhere across the screen.
  *   the behavior is similar to moving widgets or windows on a screen.
  *   custom logic required to restrict the movement of items within a set area and also prevent items from overlapping.
  *   custom logic required to detect row position and rearrange the item once it is dragged.

[react-draggable]<https://urldefense.us/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_44138408_249278002-2D48665fd4-2D9e2e-2D419f-2D9af3-2D333e06790184.gif&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=FSymA1niXwAmIXFHm04SEKImNk_8clHw-VBYxzDXsjyIxrZPGwIif_34tSCUdHrp&s=fe0TcghwbQVLgJXogGotRTmdghO8nI7miPrYyAAMTKM&e=>

**Comment by hongsudt** [comment] 2023-06-28 01:02
Yes.. This is a very good idea. Then we can personalize the facet display as well..

**Comment by carlkesselman** [comment] 2023-06-28 01:19
actually, and columns!!!

**Comment by ladukaraniket** [comment] 2023-07-01 02:38
@hongsudt @RFSH and @jrchudy ,

I've tried a bunch of options as discussed. I've attached all the possible combinations of icons that could be used for - 
- move icon (signifying that the row is draggable) **[2 icons]**
- add row icon **[2 icons]**
- delete row icon **[4 icons]**

# Text, Int and Float fields
![array-text-int](https://github.com/informatics-isi-edu/chaise/assets/44138408/4bf24220-a3be-46cc-9c40-f852b7b9f66a)![int-float-v](https://github.com/informatics-isi-edu/chaise/assets/44138408/223ee9f7-cb8e-4d82-b3d4-394a72753a24)![text-v](https://github.com/informatics-isi-edu/chaise/assets/44138408/9779be9b-84bc-4966-956f-a39229698878)


<hr>


# Boolean field
![boolean-wv](https://github.com/informatics-isi-edu/chaise/assets/44138408/735d4a71-c605-45a9-8c5d-3c84a78612be)![boolean-v](https://github.com/informatics-isi-edu/chaise/assets/44138408/54e8c850-4286-41ca-8079-4aff726760a8)


<hr>

# Date Field
### Layout 1

![date-t1-wv](https://github.com/informatics-isi-edu/chaise/assets/44138408/67018d10-650f-4d41-bfe5-b7d2c089bc47)![date-t1-v](https://github.com/informatics-isi-edu/chaise/assets/44138408/cd55a3e8-29a3-45a8-9388-b916af933967)

### Layout 2


![date-t2-wv](https://github.com/informatics-isi-edu/chaise/assets/44138408/7f55dfce-7d01-4dca-889a-cdfee0efb0ce)![date-t2-v](https://github.com/informatics-isi-edu/chaise/assets/44138408/1634a07a-0808-4917-9cd3-2f7b9a2f80ca)


<hr>

# Timestamp Field
### &emsp; &emsp; Layout 1  &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;  | &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;  Layout 2

![datetime t1 com](https://github.com/informatics-isi-edu/chaise/assets/44138408/7408ac01-9af3-46e5-9b6b-967fd30b15f3)![datetime t2 com](https://github.com/informatics-isi-edu/chaise/assets/44138408/6734534e-b69f-4f46-8e64-397cd1ceb520)

<hr>

# Increased Icon size
![Screen Shot 2023-06-30 at 19 31 33](https://github.com/informatics-isi-edu/chaise/assets/44138408/5fea424c-7527-4c6b-88d8-441d25772ef1)![Screen Shot 2023-06-30 at 19 31 50](https://github.com/informatics-isi-edu/chaise/assets/44138408/df7ceebc-4ba1-48ab-ad9b-da346c4f7c2b)

![firefox_YDHG6xNrh6](https://github.com/informatics-isi-edu/chaise/assets/44138408/a12d4cbd-4eb3-451c-be8c-01d9a1c76cc8)![firefox_dEayZhkcoU](https://github.com/informatics-isi-edu/chaise/assets/44138408/e965ba4e-d41b-4aa0-ac38-f2c7397f52dd)



![image](https://github.com/informatics-isi-edu/chaise/assets/44138408/f55643bb-b0c0-4654-8da7-4f0b5bebe58b)![firefox_WV8CPmxbCf](https://github.com/informatics-isi-edu/chaise/assets/44138408/d2a534ba-35d8-45d7-a44f-913c14a81903)

**Comment by ladukaraniket** [comment] 2023-07-07 19:54
Hey @jrchudy and @RFSH , I've updated the spacing between the + and - buttons as discussed yesterday.
I've attached the before and after snapshots for reference. Do let me know if this looks good.

# Large width
![Screen Shot 2023-07-07 at 10 05 54](https://github.com/informatics-isi-edu/chaise/assets/44138408/303707fd-4c77-44e2-8c13-4fe821d8f42c)
![Screen Shot 2023-07-07 at 10 06 11](https://github.com/informatics-isi-edu/chaise/assets/44138408/4115c91a-e7c8-47f5-9363-470d02b1ae3f)
![Screen Shot 2023-07-07 at 10 06 31](https://github.com/informatics-isi-edu/chaise/assets/44138408/847fccc1-9d1c-4dfd-9c9f-c8561dd7615b)
![Screen Shot 2023-07-07 at 10 06 43](https://github.com/informatics-isi-edu/chaise/assets/44138408/e036f2cd-7ead-4fb9-90e2-76ae599b71f8)

# Small width
### Previous
![Screen Shot 2023-07-07 at 10 13 10](https://github.com/informatics-isi-edu/chaise/assets/44138408/46778b35-f579-48a9-8d2a-6a6dc7e7323e) ![Screen Shot 2023-07-07 at 10 14 31](https://github.com/informatics-isi-edu/chaise/assets/44138408/708a95b1-823a-400d-b259-fdd8771cf318) ![Screen Shot 2023-07-07 at 10 16 51](https://github.com/informatics-isi-edu/chaise/assets/44138408/15d48f54-d46b-474f-92f2-617cf59309f7)
![Screen Shot 2023-07-07 at 10 14 58](https://github.com/informatics-isi-edu/chaise/assets/44138408/61c29821-438e-4451-a703-71d567930860)


### New
![Screen Shot 2023-07-07 at 12 49 45](https://github.com/informatics-isi-edu/chaise/assets/44138408/b8a29984-591e-4fc6-aafb-8f601638c66c) ![Screen Shot 2023-07-07 at 12 50 20](https://github.com/informatics-isi-edu/chaise/assets/44138408/f328812d-b062-4a40-b5bf-4b05d1279a9c) ![Screen Shot 2023-07-07 at 12 50 50](https://github.com/informatics-isi-edu/chaise/assets/44138408/9d5ee0db-1d77-4a1e-9a45-be06878a20d2)
![Screen Shot 2023-07-07 at 12 52 00](https://github.com/informatics-isi-edu/chaise/assets/44138408/d47fd1a6-0214-4db2-b827-591881562eac)

**Comment by jrchudy** [comment] 2023-07-20 00:33
From further discussion we decided the UI didn't have a way to "communicate" when a set was empty or allowed to be empty. This is the new proposed UI we will go with:
![image](https://github.com/informatics-isi-edu/chaise/assets/2932600/60635068-1988-49b6-896a-a16a1660baca)

The changes from what we had previously discussed include:
 - remove the `+` button from each array row
 - add an input at the bottom with `Add` button for adding more array elements
   - new values are appended to the end of the current list
   - add is disabled until value is valid
 - change `-` to a trash can
   - disable this button when there is only 1 array element and the column is not nullable
 - remove the border and shadow box
 - each array element is editable but cannot be empty
   - add validation to each array element input to validate it's not empty
 - color of grip icon should be a lighter grey

**Comment by ladukaraniket** [comment] 2023-08-02 20:32
Updated the UI as per discussion - 

- Made the font size same for list items and add-new input.
- Moved delete button to the right for Timestamp type.
- Center aligned `Add` button for Timestamp type with single row height.
- Fixed overall alignment of items.

![1NkEBJDW7e](https://github.com/informatics-isi-edu/chaise/assets/44138408/cdeacc49-e871-462c-8f71-ab0c243cc9db)

**Comment by ladukaraniket** [comment] 2023-11-08 22:57
As per commit [aeb6c199b05a031c33921f74a98c2613577d80da](https://github.com/informatics-isi-edu/chaise/pull/2340/commits/aeb6c199b05a031c33921f74a98c2613577d80da) ArrayField works as expected functionally.

It is unusable in the current state as it suffers from severe performance issues due to the way the overall form implementation is structured and needs work to optimize it.


Refactoring the ArrayField component to use the [useFieldArray](https://www.react-hook-form.com/api/usefieldarray/) hook from the react-hook-form and memoizing ArrayField and react-beautiful-dnd components improves the performance 10 folds.

Following a discussion with @RFSH and @jrchudy , the following possible ways to improve the form performance were identified
- Replace general watch with specific useWatch in the following components:
  - select all
  - array field
  - timestamp
  - foreign key
  - iframe

- Memoize inputSwitch and other components

- use `useFieldArray` for the inputs that are a collection of inputs
  - array field
  - timestamp
  - foreign key
  - iframe

**Closed** 2024-05-06 21:19 UTC
Labels: help wanted, recordedit
