### ISSUE TITLE
pass in default values to recordedit urls 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#541] opened 2016-08-22 22:13 UTC

**Comment by karlcz** [comment] 2016-11-02 22:41
@hongsudt is this redundant with the work recently done to pass a cookie name and allow pre-filled values to be provided to recordedit?

**Comment by jrchudy** [comment] 2016-11-02 22:47
This looks like the issue we opened before we thought about how to implement it. I believe the cookie implementation is a duplicate of this issue. And therefor this can be closed.

**Closed** 2016-11-07 19:37 UTC
Labels: recordedit
