### ISSUE TITLE
Generalizing facets as pseudo columns/entites

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1262] opened 2017-09-13 17:48 UTC
Once the new faceting MVP is done, I think we should broaden the scope of the new pseudo column. We should refactor the code as needed and make sure it can work in other _visible columns_  or _visible fk_ contexts to present denormalized content.  This would eliminate the need for custom SQL views in many simple denormalized presentation scenarios.

- In the recordset results table
- In the record related entities results tables
- In the modal chooser results table
- In the record main entity section

In all of the above contexts, there would be a few presentation modes:
- A facet object whose "source" field has only *outbound* foreign keys is a generalization of the current foreign key name as a visible column.
    - In entity-mode, present row_name of the single referenced record
    - In scalar mode, present the display value of the single referenced scalar
- A facet object whose "source" field has one or more *inbound* foreign keys is a generalization of today's "inline" inbound pseudo column
   - TBD: allow DBA-controlled aggregation of resulting facet?  E.g. min/max/count/array

I think that interpretation of facet pseudo columns for data presentation should ignore any embedded filters in the facet definition. That way, the same visible columns, e.g. for `*` context, might serve both for basic data presentation and also provide default filtering for the facet sidebar in the recordset app. 

Another case that was brought up by @robes which is only relevant in the record app context.. 
- A facet object whose "source" field has one or more *inbound* foreign keys is a generalization of the related table in the visible foreign-key list. 
------------------
HT: Here is a list of priorities that we should tackle (12/20/17). 
- [x] allow facet outbound-chain source as part of visible-column. The chain should be all outbound. This column should show up in the record and recordset apps. In recordset app, assume that this column is not sortable or searchable.
- [x] allow facet inbound source (or combination of inbound/outbound) as part of the visible-columns (compact/inline) or visible-fks (compact/brief). This feature is for record app only.
- [x] allow pseudo-columns of aggregate facet inbound sources. There is some correctness, performance, and ermrest readiness issues to generally support this feature. So we will only start with a subset. After discussing with @karlcz, we should be able to do the following aggregation without correctness issue: min, max, count distinct, count (faster performance, but only work for simple fk chains)
```javascript 
{ 
  "source": [...],
  "markdown_name": "...", 
  "entity": bool,
  "aggregate": "..."    /* either array/min/max/count/count distinct */
}
```
- [x] make outbound fk pseudo-column sortable? 
- [x] allow pseudo-columns of array aggregate of facet inbound sources. This depends on new ermrest feature.

**Comment by karlcz** [comment] 2017-11-30 20:16
Another wrinkle here is that a DBA may want to ask for a path-based psuedo-column to be loaded into the templating environment, but not actually displayed as a new column of its own. Rather, they just want to access some of this denormalized content to improve the presentation of an existing column via templated markdown.

This may need a new kind of annotation since it doesn't seem to fit the visible columns nor visible foreign keys concepts very well...

@hongsudt @robes

**Comment by hongsudt** [comment] 2017-12-13 20:04
@karlcz @robes @ljpearlman lets start by designing the annotation syntax..

**Comment by karlcz** [comment] 2017-12-14 23:39
As a starting point, we should simply allow the same notation currently used in individual facet controls for the "filter" context within the list for other contexts.  i.e.  `{"source": [...], "markdown_name": "...", "entity": bool}` as an element in a visible column list.

When we add support for the filter elements within the source path for faceting, we should also add them here. The only thing that might be extra for pseudo column notation is if we want to allow for aggregate functions or other value transformations to be made available.  However, if we are unsure what capabilities are useful here, I would defer adding such extensions.  We may be able to get some reasonable mileage out of just having arrays of values, particularly in combination with the new handlebars-based template engine which could allow the DBA to transform the final values in other ways on the client side...

**Comment by hongsudt** [comment] 2017-12-19 23:34
Should we define `aggregates` for aggregate functions to be mapped to ermrest aggregate functions e.g.  min/max/count/array?

**Comment by hongsudt** [comment] 2017-12-19 23:46
also, what's the implication of this pseudo-column on the regex search? Does ermrest support this?

**Comment by RFSH** [comment] 2018-03-06 19:47
For adding outbound-chain sources to recordset we simply are adding them to the list of projection list while we're creating the request for main entity. But for other cases we cannot simply do that since the addition of join will result in additional rows in the returned data and it will have performance and correctness problem. Therefore we decided to do the following for supporting this:

After getting the data for the main page,
  - If the table didn't have any shortest key, don't return any data (We cannot easily support this). 
  - Gather the values of the shortestkeys for all the rows. Generate a link in the following format for each of the sources:
     ```
     <main table url>/<key value pairs of all the shortestkey values>/<join path based on the given source>/<shortest key>;<aggregate column>
     ```
  - Go through the returned result and map the value to the corresponding row.

This way, we will do additional reads for each of the columns that we want to show in the table. Since we're adding all the `key=value`s to the path, we should be cautious of URL limit. Therefore we might end up sending multiple requests to ermrest. We can also limit the number of rows that we want to support.

**Comment by RFSH** [comment] 2018-04-10 18:34
One of the remaining tasks is adding aggregates in recordset app. This requires changes to the flow-control. The following should be the order of requests in flow-control:

1. Main page
2. (_**New**_) if main page is available) Aggregate data
3. Faceting data
4. (if main page is available) Total count

**Comment by RFSH** [comment] 2018-05-17 00:50
The last piece of this task which is adding aggregates to table views (recordset app and related/inline entities in record app) has been done.
DBAs should be able to use aggregate columns in any read-only contexts.

**Comment by RFSH** [comment] 2018-05-23 18:35
`array` has been added to the list of available aggregate functions that data modelers can use. Currently we're relying on Javascript sort function, to sort the result that is returned from ERMrest. The array might also include duplicate values and it also returns all of the values that exist in the database. So it can be a huge dataset. It should be used with cautious.

**Comment by RFSH** [comment] 2018-11-27 22:45
I am going to close this issue. We have already received several feedback on the `array` aggregate feature and have gone through some cycle of changes.

**Closed by RFSH** 2018-11-27 22:45 UTC
